# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  focalpoints.africa:
    site_hosts:
      - canonical: fp.wacren.net
        redirects:
         - fp.ubuntunet.net
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:ubuntunet/wordpress.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: develop
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
